### ISSUE TITLE
OK with watch TTGO V2 but KO with V1

### ISSUE THREAD

**Issue by picpic020960** [vshymanskyy/ViperIDE#3] opened 2024-06-17 18:00 UTC
Bonjour,
With the ttgo watch V2 , the connection  IS ok and the demo script run fine ( no explorer file but old version of micropython v1.14 (with lvgl)) (A)
But with ttgo watch V1 the watch IS no found : driver issue , webserial issue , webusb issue ?
Not viper-ide issue but it's not easy to find information about this problem (B)
Thank's for help
Regards

NB : on android 

(A) save script as test.py is OK.  walk is OK but file explorer tree always empty.
    at begin , listdir with only f:<fine name>:<size>  , no d:<...> 

(B) USB single serial is OK but CP210x KO on chrome android or chrome windows

**Comment by vshymanskyy** [comment] 2024-06-18 09:58
Duplicate of https://github.com/vshymanskyy/ViperIDE/issues/2

CP210x probably doesn't work on Android

**Closed as completed by vshymanskyy** 2024-06-18 09:58 UTC

**Comment by vshymanskyy** [comment] 2024-06-19 21:31
Please check again with ViperIDE v0.3.1
