### ISSUE TITLE
Timeout with files Big  tree (android)

### ISSUE THREAD

**Issue by picpic020960** [vshymanskyy/ViperIDE#7] opened 2024-06-20 19:38 UTC
[re]Bonjour ,
On m'y watch V2 , files big  tree and 'timeout' message ; then the listdir on the REPL console.
So the file explorer IS empty.
I have old version of micropython (1.14) but the other fonctions are OK : run script , packages , soft/hard reset.

One trick ?
![Screenshot_20240620-214343](https://github.com/vshymanskyy/ViperIDE/assets/16744082/83dee326-8eb5-4f85-9ada-8a0190fb19de)

Thank's for help
NB : good job

**Comment by vshymanskyy** [comment] 2024-06-20 20:18
This is interesting... How many files do you have on your device?

**Comment by vshymanskyy** [comment] 2024-06-20 20:56
There's no particular interest in supporting outdated MPY versions. Why do you use v1.14? It's 3.5 years old.
Can you try a recent version?

**Comment by vshymanskyy** [comment] 2024-06-20 22:33
Please try again with 0.3.1 build 2024-06-20 22:32:12
@picpic020960

**Comment by Pedrocasf** [comment] 2024-06-21 02:46
I can confirm that the issue still happens with the latest micropython preview v1.24.0-preview.47.g88513d122 (2024-06-19)  when using BLE on my ESP32-S3 on both Linux and Android.

**Comment by vshymanskyy** [comment] 2024-06-21 05:36
On the screenshot above, you're using a USB connection. Does it work?

**Comment by picpic020960** [comment] 2024-06-21 05:39
> Il n'y a aucun intérêt particulier à prendre en charge les versions MPY obsolètes. Pourquoi utilisez-vous la v1.14 ? Il a 3,5 ans. Pouvez-vous essayer une version récente ?

V1.14 with lvgl : not easy to build

**Comment by rkompass** [comment] 2024-06-21 09:05
Hello Volodimir,

I have this same error (Timeout reached before finding the ending sequence) when connecting the w600 through the web_repl.
The hierarchy of the few files on the board at first is displayed correctly. Terminal works.
But: When I double-click a file to open in the editor, (or create a new file, after entering it's name) then this error occurrs.
The terminal then also stops echoing my keystrokes.
At the w600 primary terminal (screen /dev/ttyUSB0 115200)  then I see (if file doubleclick)
```
raw REPL; CTRL-B to exit
>
```
is displayed without accepting any input (tried also the Ctrl-B: no reaction).

**Comment by vshymanskyy** [comment] 2024-06-21 10:10
@rkompass are you sure your issue is related?

@picpic020960 do you have an issue with BLE or USB connection, it is unclear.
Also, did you try with the latest version?

**Comment by rkompass** [comment] 2024-06-21 10:26
I can open a new issue for w600.
Thought it might be related as the error message (in the red box, right above) is the same.
I'm not sure, though.

**Comment by vshymanskyy** [comment] 2024-06-21 10:27
Timeout can happen due to a broad range of factors

**Comment by picpic020960** [comment] 2024-06-21 12:16
Better !
File explorer OK AT begin.
Load file OK but save After update KO : file size = 0
New file : save KO also After re-connect.

Improvement : zoom and proportionnal font : it's better for eyes on Android tablet

**Comment by vshymanskyy** [comment] 2024-06-21 12:24
The initial issue was resolved, so closing this. Please create new tickets for each problem

**Closed as completed by vshymanskyy** 2024-06-21 12:24 UTC
Labels: bug
